[book]
authors = ["Kenton Hamaluik"]
language = "en"
multilingual = false
src = "src"
title = "Example"

[preprocessor.puml]
command = "/home/kenton/Documents/projects/mdbook-puml/target/debug/mdbook-puml"
renderer = ["html"]

